title = "Penta Global"
theme = "airspace-hugo"
DefaultContentLanguage = "en-us"
baseURL = "/"

[menu]
  [[menu.header]]
    weight = 2
    name = "PROJECT"
    url = "/work"
  [[menu.header]]
    weight = 4
    name = "BLOG"
    url = "/blog"
  [[menu.header]]
    weight = 3
    name = "ABOUT"
    url = "/service"
  [[menu.header]]
    weight = 10
    name = "CONTACT US"
    url = "/contact"
#  [[menu.header]]
#    weight = 6
#    name = "RESOURCES"
#    url = "/resources"
  [[menu.header]]
    weight = 7
    name = "AMBASSADOR"
    url = "/ambassador"
  [[menu.header]]
    weight = 8
    name = "ROADMAP"
    url = "/roadmap"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "/#intro"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "/contact"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "/service"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "/blog"

[languages]
[languages.en-us]
title = "Penta Global"
languageName = "English"
weight = 1
contentDir = "content/english"
dataDir = "data/english"

[languages.zh-cn]
title = "Penta Global"
languageName = "简体中文"
weight = 2
contentDir = "content/chinese-simplified"
dataDir = "data/chinese-simplified"

[languages.ko]
title = "Penta Global"
languageName = "한국어"
weight = 3
contentDir = "content/korean"
dataDir = "data/korean"

[languages.fr]
title = "Penta Global"
languageName = "Français"
weight = 4
contentDir = "content/french"
dataDir = "data/french"

[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

 #date_format = "6 January 2006"
 date_format = "Mon, Jan 2, 2006"

  #home = "Home"